### PR TITLE
Updates to ReadMe to get more clarity

### PR DESCRIPTION
**Pull request by rkadam**
Happy New Year Wes!
Going through your commandlinepoweruser videos and on as part of Video 5, started using this theme. I was stuck on Powerline installation and I'm hoping this adds more clarity to help users who like to use theme.

Thank you for sharing.
Raju

### CODE REVIEW

**Comment by wesbos** [comment]
Hey - thanks so much for the edits. These are great edits but not something that I want in my terminal - you can feel free to fork it and make your own theme. 

thanks again1

**Comment by rkadam** [comment]
Good Morning Wes.

When I created PR, I really wanted to update README in main REPO to get clarity around how to install *Powerline Fonts*

Later I updated my fork to make changes that I really wanted for myself and committed to fork. But it seems my earlier PR picked up these changes and shown all together. which I didn't want either.

Raju

**Comment by wesbos** [comment]
Ah - can you submit a new PR with just the readme edits?

**Comment by rkadam** [comment]
Yeh I'm trying to figure out how to create a new PR with specific commit.
Do you have any idea? Google says I should do cherry pick so. Trying to
understand what needs to be done.

But yeh, I would love to update documentation. That was the objective.
Thank you for listening.

BTW I love commandlinepoweruser series. Learned lot of stuff. I've also
bought Sublime Text book and video series. Hoping to catchup on it.

cheers,
Raju

**Comment by wesbos** [comment]
Yeah - so first make a new branch forked from master. 

then `git cherry-pick 18d6f64` 

Then submit a PR from that branch. 

Or just edit the readme.md from github again :) 

Glad you have been enjoying everything!

**Comment by rkadam** [comment]
sure thing. Created another PR for README updates #18

**Pull request closed without merging**
