### PR TITLE
Ported colour scheme to a mintty environment.

### PR DESCRIPTION
**Pull request by AshleyWright**
This makes the colour scheme usable in any instance of MinTTY, for example Babun. Also tested in ConEmu.
image

### CODE REVIEW

**Comment by wesbos** [comment]
Amazing - could you add something to the readme about support for this, and how to install it?

**Comment by AshleyWright** [comment]
Just the colour scheme in a MinTTY instance, or getting the environment I suggested above working. The former, yes; latter, with more difficulty.

**Comment by wesbos** [comment]
Oh that isn't the regular ZSH shell? 

The colour scheme for starters

**Comment by AshleyWright** [comment]
What I'm using is ZSH in a MinTTY instance provided by Babun wrapped up in ConEmu. It would work with just ZSH in MinTTY, I've just chosen to make it more complex for my own use.

**Comment by wesbos** [comment]
Ah okay - yep then just the MinTTY instructions to get the colour scheme running :)

**Comment by AshleyWright** [comment]
See Pull Request https://github.com/wesbos/Cobalt2-iterm/pull/12 .

**Pull request merged**
